version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn install
  build:
    commands:
      - mkdir .server
      - cp -rf $CODEBUILD_SRC_DIR_assets .server
      - yarn build:server
      - yarn package:server

artifacts:
  base-directory: .server
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'
